### ISSUE TITLE
TypeError while running catalog cleanup

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.catalogcleanup#19]
While trying to run catalog cleanup in dry run mode I get the following error:

```pytb
2018-09-19T17:22:54 ERROR collective.catalogcleanup Cannot handle brain at 899c94317912479c8cac6d1949a6904a.
Traceback (most recent call last):
  File "/opt/plone/buildout/eggs/collective.catalogcleanup-1.8.0-py2.7.egg/collective/catalogcleanup/browser.py", line 341, in get_object_or_status
    obj = getattr(brain, getter)()
  File "/opt/plone/buildout/eggs/plone.app.referenceablebehavior-0.7.7-py2.7.egg/plone/app/referenceablebehavior/referenceable.py", line 29, in getTargetObject
    obj = referenceable.IReferenceable(obj)
TypeError: ('Could not adapt', <Image at /foo/Plone/bar.jpg>, <InterfaceClass Products.Archetypes.interfaces.referenceable.IReferenceable>)
------
2018-09-19T17:22:54 ERROR Zope.SiteErrorLog 1537388574.960.188944346331 http://localhost:8181/brazilgovnews/idg/@@collective-catalogcleanup
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module collective.catalogcleanup.browser, line 78, in __call__
  Module collective.catalogcleanup.browser, line 202, in check_references
   - __traceback_info__: reference_catalog
  Module collective.catalogcleanup.browser, line 341, in get_object_or_status
   - __traceback_info__: [<Reference sid:dc2534d5be1947aa93927656deff15ac tid:66d107304f5c43deb90600ccaebe3491 rel:isReferencing>, 'getTargetObject', '899c94317912479c8cac6d1949a6904a']
  Module plone.app.referenceablebehavior.referenceable, line 29, in getTargetObject
TypeError: ('Could not adapt', <Image at /foo/Plone/bar.jpg>, <InterfaceClass Products.Archetypes.interfaces.referenceable.IReferenceable>)
```

plone.app.referenceablebehavior is available but not installed; installing it makes no difference on the error.

any hints?

**Comment by mauritsvanrees** [comment]
Fixed in 1.9.0.
